- hosts: local
  user: root
  roles:
    - role: homebrew
      tags: homebrew
    - role: mas
      tags: mas
    - role: ruby
      tags: ruby
    - role: python
      tags: python
    - role: node
      tags: node
