- block:
  - name: List installed apps
    command: mas list
    register: mas_list
    check_mode: no
    changed_when: false

  - name: Install
    command: mas install "{{ item.id }}"
    with_items: "{{ apps }}"
    when: (item.id | string) not in mas_list.stdout
