- block:
  - name: Update
    homebrew:
     update_homebrew: true

  - name: Tap
    homebrew_tap:
      name: "{{ item }}"
      state: present
    with_items: "{{ taps }}"

  - name: Install Cask
    homebrew_cask:
      name: "{{ item.name }}"
      state: installed
      install_options: "appdir=/Applications"
      accept_external_apps: true
    with_items: "{{ cask_packages }}"

  - name: Install
    homebrew:
      name: "{{ item.name }}"
      state: "{{ item.state | default('present') }}"
      #state: "{{ item.state }}"
    with_items: "{{ packages }}"
