taps:
  - homebrew/cask

packages:
  - name: ansible
  - name: git
  - name: jq
  - name: lv
  - name: mas
  - name: tmux
  - name: tree
  - name: zsh

cask_packages:
#  - name: alfred
#  - name: atom
  - name: clipy
  - name: google-chrome
  - name: iterm2
  - name: skype
  - name: slack
  - name: spectacle
  - name: vivaldi

